### ISSUE TITLE
make_consensus_enformer.py: error: Incorrect number of arguments, expected 3 arguments but got 4

### ISSUE THREAD

**Issue by houruiyan** [ni-lab/personalized-expression-benchmark#2]
Hi, thank you very much for your detailed description for your process. I want to get the consensus sequence following your code, however, I cannot run make_consensus_enformer.py smoothly. Hope to get your response. Thank you! 

![image](https://github.com/ni-lab/personalized-expression-benchmark/assets/56068158/d97b62c2-6693-4974-a17d-de01d2480e08)

**Comment by pkathail** [comment]
I've updated the script to expect 4 arguments (ref_fasta_dir, vcf_dir, genes_csv, sample_file) instead of 3, which should fix this error!

**Comment by houruiyan** [comment]
Thank you for your reply!
