### ISSUE TITLE
Could you please provide the demo of hdr.txt and sample_file in process_vcf.py 

### ISSUE THREAD

**Issue by houruiyan** [ni-lab/personalized-expression-benchmark#3]
Hi, I want to get the cleaned vcf file. When I run process_vcf.py, I cannot run it smoothly because I do not know the format of hdr.txt and same_length_inds.txt. Could you give us several example? 

Thanks you very much!

**Comment by richardshuai** [comment]
Hi! We just uploaded the relevant files under data/baselines. Hope that helps, let us know if you have any other questions.

**Comment by houruiyan** [comment]
Thank you for your response!
